version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PGHOST=${PGHOST:-103.150.93.88}
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=${POSTGRES_DB}
      - PGPORT=5432
      - ACCESS_TOKEN_KEY=${ACCESS_TOKEN_KEY}
      - REFRESH_TOKEN_KEY=${REFRESH_TOKEN_KEY}
    restart: unless-stopped

volumes:
  postgres_data: