name: Continuous Integration

on:
  pull_request:
    branches: [ main ]
  # push:
  #   branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v18.20.6'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # - name: Run database migrations
      #   run: npm run migrate:test up
      #   env:
      #     PGHOST: ${{ secrets.PGHOST }}
      #     PGUSER: ${{ secrets.POSTGRES_USER }}
      #     PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      #     PGDATABASE: ${{ secrets.POSTGRES_DB }}
      #     PGPORT: 5432
          
      - name: Run tests
        run: npm run test
        env:
          PGHOST: ${{ secrets.PGHOST }}
          PGUSER: ${{ secrets.POSTGRES_USER }}
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PGDATABASE: ${{ secrets.POSTGRES_DB }}
          PGPORT: 5432
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}